version: 0.2

env:
  variables:
    SRC_DIR: src/github.com/buzzsurfr/harbormaster

phases:

  install:
    commands:

      # AWS Codebuild Go images use /go for the $GOPATH so let's symlink our
      # application source code into that directory structure.
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/handler"

      # Install golint
      - go get -u github.com/golang/lint/golint

      # Install Testify to use common assertions and mocks in tests
      - go get -u github.com/stretchr/testify

  pre_build:
    commands:

      # Make sure we're in the project directory within our GOPATH
      - cd "/go/src/handler"
      
      # Added for dep capability
      # - mkdir -p ../github.com/buzzsurfr/harbormaster
      # - mv * ../github.com/buzzsurfr/harbormaster
      # - mv ../github.com .
      # - cd github.com/buzzsurfr/harbormaster

      # Fetch all dependencies
      # - go get ./...
      - dep ensure

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Check for common Go application problems with 'go tool vet'
      - go tool vet .

      # Run all tests included with our application
      - go test .

  build:
    commands:

      # Build our go application
      - go build -o main
      - go build -o bin/ClusterList cluster/list/main.go
      - go build -o bin/ClusterDetail cluster/detail/main.go
      - go build -o bin/NodeList node/list/main.go

      # Copy static assets to S3, and package application with AWS CloudFormation/SAM
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml
